In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])   #array 

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
b = np.array([(1.4,2,3.3), (23.4,34,12)], dtype = float)

In [5]:
b

array([[ 1.4,  2. ,  3.3],
       [23.4, 34. , 12. ]])

In [6]:
c = np.array([[(1,2,3), (23,34,12)],[(1,4,2), (2,33,12)]],dtype = float)

In [7]:
c

array([[[ 1.,  2.,  3.],
        [23., 34., 12.]],

       [[ 1.,  4.,  2.],
        [ 2., 33., 12.]]])

In [8]:
c.ndim  # shows number of dimension (ndim)

3

In [9]:
z = np.zeros([3,4],dtype = int)  # to create 0's array

In [10]:
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
x = np.ones((4,3,2))  

In [12]:
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [13]:
x.ndim

3

In [14]:
x1 = np.ones((4,3,))  

In [15]:
x1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
x1.ndim

2

In [17]:
 d = np.arange(10,23,7,)

In [18]:
d

array([10, 17])

In [19]:
lp = np.linspace(0,2,9)

In [20]:
lp

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [21]:
f = np.eye(2)

In [22]:
f

array([[1., 0.],
       [0., 1.]])

In [23]:
f1 = np.eye(3)

In [24]:
f1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
e = np.empty((3,2))  #random variables #
e

array([[ 1.4,  2. ],
       [ 3.3, 23.4],
       [34. , 12. ]])

In [26]:
r = np.random.random([2,2])
r

array([[0.81972177, 0.50484464],
       [0.51327842, 0.12119207]])

In [27]:
d.shape



(2,)

In [28]:
d.size

2

In [29]:
len(d)

2

In [30]:
d.dtype

dtype('int32')

In [31]:
e.dtype

dtype('float64')

In [32]:
e.dtype.name

'float64'

In [33]:
e1 = e.astype(int)  #e1 is to store the new data type of 'e', where e was previously float

In [34]:
e1.dtype.name

'int32'

In [35]:
np.sum(d)

27

In [36]:
np.min(d)

10

In [37]:
np.max(d)

17

In [38]:
e

array([[ 1.4,  2. ],
       [ 3.3, 23.4],
       [34. , 12. ]])

In [39]:
np.max(e, axis = 0)  # column wise max value of each column

array([34. , 23.4])

In [40]:
np.max(e, axis = 1) # Row wise

array([ 2. , 23.4, 34. ])

In [41]:
np.mean(e)

12.683333333333332

In [42]:
np.median(e)

7.65

In [43]:
np.std(e)

12.24206091945125

In [44]:
b

array([[ 1.4,  2. ,  3.3],
       [23.4, 34. , 12. ]])

In [45]:

b.cumsum(axis=1)

array([[ 1.4,  3.4,  6.7],
       [23.4, 57.4, 69.4]])

In [46]:
np.mean(a)

3.0

In [47]:
a.mean()

3.0

In [48]:
np.corrcoef(b)

array([[ 1.        , -0.68468735],
       [-0.68468735,  1.        ]])

In [49]:
e.sort(axis = 0)

In [50]:
e

array([[ 1.4,  2. ],
       [ 3.3, 12. ],
       [34. , 23.4]])

In [51]:
np.sort(b, axis = 0)

array([[ 1.4,  2. ,  3.3],
       [23.4, 34. , 12. ]])

In [52]:
a

array([1, 2, 3, 4, 5])

In [53]:
a[0:2]

array([1, 2])

In [54]:
b

array([[ 1.4,  2. ,  3.3],
       [23.4, 34. , 12. ]])

In [55]:
b[0:1,1]

array([2.])

In [56]:
b[:1]

array([[1.4, 2. , 3.3]])

In [57]:
b1 = np.transpose(b)

In [58]:
b1

array([[ 1.4, 23.4],
       [ 2. , 34. ],
       [ 3.3, 12. ]])

In [59]:
c

array([[[ 1.,  2.,  3.],
        [23., 34., 12.]],

       [[ 1.,  4.,  2.],
        [ 2., 33., 12.]]])

In [60]:
c1 = c.ravel()

In [61]:
c1

array([ 1.,  2.,  3., 23., 34., 12.,  1.,  4.,  2.,  2., 33., 12.])

In [62]:
b.shape

(2, 3)

In [63]:
b

array([[ 1.4,  2. ,  3.3],
       [23.4, 34. , 12. ]])

In [64]:
b.reshape(3,2)

array([[ 1.4,  2. ],
       [ 3.3, 23.4],
       [34. , 12. ]])

In [65]:
b.reshape(6,1)

array([[ 1.4],
       [ 2. ],
       [ 3.3],
       [23.4],
       [34. ],
       [12. ]])

In [66]:
a2 = (1,2,3)

In [67]:
print(a2)
print(b)

(1, 2, 3)
[[ 1.4  2.   3.3]
 [23.4 34.  12. ]]


In [68]:
combine = np.vstack((a2,b))

In [69]:
combine

array([[ 1. ,  2. ,  3. ],
       [ 1.4,  2. ,  3.3],
       [23.4, 34. , 12. ]])

In [70]:
# sklearn
from sklearn import preprocessing,datasets

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [73]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer

In [74]:
# Dataset creation
x = np.random.random ((10,5))

In [75]:
x

array([[0.50704599, 0.56022241, 0.03111433, 0.59524263, 0.36715547],
       [0.30239754, 0.93597829, 0.39993692, 0.76994818, 0.6939    ],
       [0.38797658, 0.57033415, 0.57420082, 0.90918653, 0.37525767],
       [0.16941962, 0.36817285, 0.63246046, 0.40178288, 0.78611899],
       [0.7998475 , 0.08769962, 0.53611038, 0.34805335, 0.31210288],
       [0.94546173, 0.0581985 , 0.14672717, 0.06166369, 0.57051191],
       [0.27631613, 0.47139378, 0.77596512, 0.44595194, 0.92023212],
       [0.59230412, 0.81954315, 0.82144724, 0.13499927, 0.01114341],
       [0.33078404, 0.5990514 , 0.38095208, 0.23432959, 0.77090056],
       [0.51857084, 0.09816903, 0.5532824 , 0.75690877, 0.688103  ]])

In [76]:
y = np.array(['m','m','f','f','m','f','m','m','f','f'])

In [77]:
x [x<0.7] = 0
x

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.93597829, 0.        , 0.76994818, 0.        ],
       [0.        , 0.        , 0.        , 0.90918653, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.78611899],
       [0.7998475 , 0.        , 0.        , 0.        , 0.        ],
       [0.94546173, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.77596512, 0.        , 0.92023212],
       [0.        , 0.81954315, 0.82144724, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.77090056],
       [0.        , 0.        , 0.        , 0.75690877, 0.        ]])

In [78]:
#data split
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.3, random_state=0)
print("x Training data shape:", x_train.shape)
print("x Training data shape:", x_test.shape)
print("y Training data shape:", y_train.shape)
print("y Training data shape:", y_test.shape)

x Training data shape: (7, 5)
x Training data shape: (3, 5)
y Training data shape: (7,)
y Training data shape: (3,)


In [79]:
#Data preprocessing
#1. Standardization
# here we want to impport a lib so add it above for simplicity 
# from sklearn.preprocessing import StandardScaler

In [80]:
b = np.array([(1.5,2,3),(4,5,6)], dtype=float)

In [81]:
print(b)
print(b.mean())
print(b.std())

[[1.5 2.  3. ]
 [4.  5.  6. ]]
3.5833333333333335
1.5920810978785667


In [82]:
scaler = StandardScaler()
b_std = scaler.fit_transform(b)
print (b_std)

[[-1. -1. -1.]
 [ 1.  1.  1.]]


In [83]:
print(b_std.mean())
print(b_std.std())

0.0
1.0


In [84]:
std_X = scaler.fit_transform(x_train)
std_xtest = scaler.transform(x_test)
print(std_X)
print(std_xtest)
print(std_X.mean())

[[-0.40824829 -0.63051695 -0.63209694  1.56215491 -0.62973829]
 [-0.40824829  1.72265924 -0.63209694  1.59996132 -0.62973829]
 [-0.40824829 -0.63051695  1.5172518  -0.63242325  1.7475789 ]
 [-0.40824829  1.42992553  1.64323288 -0.63242325 -0.62973829]
 [-0.40824829 -0.63051695 -0.63209694 -0.63242325  1.40111256]
 [-0.40824829 -0.63051695 -0.63209694 -0.63242325 -0.62973829]
 [ 2.44948974 -0.63051695 -0.63209694 -0.63242325 -0.62973829]]
[[-0.40824829 -0.63051695 -0.63209694  2.00366841 -0.62973829]
 [-0.40824829 -0.63051695 -0.63209694 -0.63242325  1.36179744]
 [ 2.0093584  -0.63051695 -0.63209694 -0.63242325 -0.62973829]]
-1.9032394707859827e-17


In [85]:
#2. Normalization
#from sklearn.preprocessing import Normalizer

In [86]:
norm = Normalizer()
norm_X = norm.fit_transform(x_train)
norm_xtest = norm.transform(x_test)

In [87]:
# Labelencoder or onehot encoder
from sklearn.preprocessing import LabelEncoder
lbn = LabelEncoder()
print(y)
y_enc = lbn.fit_transform(y)
print(y_enc)


['m' 'm' 'f' 'f' 'm' 'f' 'm' 'm' 'f' 'f']
[1 1 0 0 1 0 1 1 0 0]


In [88]:
# Algorithms
#Linear regression

from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.svm import SVC, SVR
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import *

In [89]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

In [90]:
#2. Unsupervised
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
#---------------

In [91]:
# Model Fitting
mlp = MLPClassifier()
mlp.fit(std_X,y_train)

c:\users\abhis\appdata\local\programs\python\python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [92]:
#prediction
y_pred = mlp.predict(std_xtest)